name: Run ZAP Baseline Scan on Deployed Application

on:
  push:
    branches:
      - master  # Trigger the workflow when pushing to the master branch

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Run ZAP Baseline Scan
    - name: Run ZAP Baseline Scan
      # uses: zaproxy/action-baseline@v0.14.0
      run: |
        # Pull the official OWASP ZAP Docker image
        docker pull zaproxy/zap-stable
  
        # Run ZAP Baseline scan and mount the output directory
        docker run --rm -v $(pwd):/zap/wrk --network=host \
          -t zaproxy/zap-stable zap-baseline.py \
          -t http://34.239.245.207:5050 \
          -J report_json.json \
          -r zap-report.html  # Save the report to the mounted directory
     # Upload the generated ZAP report as an artifact
    - name: Upload ZAP report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: zap-report.html  # Path to the generated report
