name: Run ZAP Baseline Scan on Deployed Application

on:
  push:
    branches:
      - master  # Trigger the workflow when pushing to the master branch

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Run ZAP Baseline Scan
    - name: Run ZAP Baseline Scan
      uses: wangjiaqi1990/zap-baseline-scan@v1
      with:
        target: 'http://34.239.245.207:5050'  # Replace with the public IP and port of your EC2 instance
        fail-on-high-risks: 'false'  # Set to 'true' if you want to fail the job on high-risk vulnerabilities
        report-file: 'zap-report.html'
      env:
        ZAP_HOST: 'localhost'
        ZAP_PORT: '8090'  # Port where ZAP is running (default is 8090)
